name: Star Ocean 3 US overlay 0072-00 (cmc.bin)
sha1: 37ebf735ccc1d79833f633ba105ea87d444f4406
sha256: 6cee83863b08a0603c345c819c54e320ff59393889184c81ed681dc76306bd62
options:
  basename: 0072-00
  target_path: disc/us-disc1/modules/0072-00.bin
  base_path: ../..
  platform: ps2
  compiler: MWCCPS2
  asm_path: build/overlays/0072-00/asm
  asset_path: build/overlays/0072-00/bin
  src_path: src/overlays/0072-00
  build_path: build/overlays/0072-00
  ld_script_path: build/overlays/0072-00/overlay.ld
  generated_asm_macros_directory: build/overlays/0072-00/include
  cache_path: build/overlays/0072-00/splat.cache
  undefined_funcs_auto_path: build/overlays/0072-00/undefined_funcs.ld
  undefined_syms_auto_path: build/overlays/0072-00/undefined_syms.ld
  create_c_files: true
  make_full_disasm_for_code: true
  auto_decompile_empty_functions: false
  generated_c_preamble: '#include "include_asm.h"'
  asm_inc_header: |
    .set noat
    .set noreorder
  migrate_rodata_to_functions: false
  subalign: 4
  find_file_boundaries: false
  disasm_unknown: true
  gp_value: 0x1bdff0
  generated_macro_inc_content: |
    .set Q, $Q
    .set ACC, $ACC
    .set I, $I
    .set R, $R
segments:
  - name: header
    type: bin
    start: 0x0
    vram: 0x348380
  - name: text
    type: code
    start: 0x40
    vram: 0x3483c0
    subalign: 16
    subsegments:
      - [0x40, c, text]
  - [0x12f80, bin, data]
  - [0x13080]
