name: Star Ocean 3 US Field overlay 1067-00 (header y)
sha1: ac30f64711db100d67762f197d2e0a9dff406add
sha256: 15c14acfb1b6682c20798ac557d956f87e06184afb06709c798afddf47ac4ffd
options:
  basename: 1067-00
  target_path: disc/us-disc1/modules/1067-00.bin
  base_path: ../..
  platform: ps2
  compiler: MWCCPS2
  asm_path: build/overlays/1067-00/asm
  asset_path: build/overlays/1067-00/bin
  src_path: src/overlays/1067-00
  build_path: build/overlays/1067-00
  ld_script_path: build/overlays/1067-00/overlay.ld
  generated_asm_macros_directory: build/overlays/1067-00/include
  cache_path: build/overlays/1067-00/splat.cache
  symbol_addrs_path: [config/symbols/1067-00_symbol_addrs.txt]
  reloc_addrs_path: [config/relocations/1067-00_reloc_addrs.txt]
  undefined_funcs_auto_path: build/overlays/1067-00/undefined_funcs.ld
  undefined_syms_auto_path: build/overlays/1067-00/undefined_syms.ld
  create_c_files: true
  make_full_disasm_for_code: true
  auto_decompile_empty_functions: false
  generated_c_preamble: '#include "include_asm.h"'
  asm_inc_header: |
    .set noat
    .set noreorder
  migrate_rodata_to_functions: false
  subalign: 4
  find_file_boundaries: false
  disasm_unknown: true
  gp_value: 0x1bdff0
  global_vram_start: 0x1B6000
  global_vram_end: 0x1B7000
  generated_macro_inc_content: |
    .set Q, $Q
    .set ACC, $ACC
    .set I, $I
    .set R, $R
segments:
  - name: header
    type: bin
    start: 0x0
    vram: 0x1dd380
  - name: text
    type: code
    start: 0x40
    vram: 0x1dd3c0
    subalign: 16
    subsegments:
      # Linker padding: .text starts on a 128-byte boundary after the 64-byte MWo3 header.
      - [0x40, pad, text_align]
      - [0x80, cpp, text_001DD3C0]
      - [0x1A00, cpp, text_001DED80]
      - [0x4210, cpp, text_001E1590]
      - [0x98D0, cpp, text_001E6C50]
      - [0x10460, cpp, text_001ED7E0]
      - [0x1C7F0, cpp, text_001F9B70]
      - [0x204E0, cpp, text_001FD860]
      - [0x21EE0, cpp, text_001FF260]
      - [0x23390, cpp, text_00200710]
      - [0x24EC0, cpp, text_00202240]
      - [0x2A200, cpp, text_00207580]
      - [0x2A770, cpp, text_00207AF0]
      - [0x30620, c, text_0020D9A0]
      - [0x31130, c, text_0020E4B0]
      - [0x32670, c, text_0020F9F0]
      - [0x351E0, c, text_00212560]
      - [0x3AD70, c, text_002180F0]
      - [0x40800, c, text_0021DB80]
      - [0x42800, c, text_0021FB80]
      - [0x4E110, c, text_0022B490]
      - [0x508F0, c, text_0022DC70]
      - [0x5DE50, c, text_0023B1D0]
      - [0x60010, c, text_0023D390]
      - [0x60910, c, text_0023DC90]
      - [0x6F130, c, text_0024C4B0]
      - [0x70B00, c, text_0024DE80]
      - [0x76E70, c, text_002541F0]
      - [0x78150, c, text_002554D0]
      - [0x7A3D0, c, text_00257750]
      - [0x810A0, c, text_0025E420]
      - [0x83430, c, text_002607B0]
      - [0x86330, c, text_002636B0]
      - [0x910E0, c, text_0026E460]
      - [0x91A90, c, text_0026EE10]
      - [0x94FE0, c, text_00272360]
      - [0x963A0, cpp, text_00273720]
      - [0x99150, cpp, text_002764D0]
      - [0xA0000, c, text_0027D380]
      - [0xA11A0, c, text_0027E520]
      - [0xB0EC0, c, text_0028E240]
      - [0xB11B0, c, text_0028E530]
      - [0xB4800, c, text_00291B80]
      - [0xB59A0, c, text_00292D20]
      - [0xB6120, c, text_002934A0]
      - [0xB6290, cpp, text_00293610]
      - [0xC1660, cpp, text_0029E9E0]
      - [0xD1660, cpp, text_002AE9E0]
      - [0xDF190, cpp, text_002BC510]
      - [0xE0D20, cpp, text_002BE0A0]
      - [0xE1710, cpp, text_002BEA90]
      - [0xE3160, cpp, text_002C04E0]
      - [0xED840, cpp, text_002CABC0]
      - [0xF0010, cpp, text_002CD390]
      - [0xF1770, cpp, text_002CEAF0]
      - [0xF6850, cpp, text_002D3BD0]
      - [0xF7EE0, cpp, text_002D5260]
      - [0xFB090, cpp, text_002D8410]
      - [0xFCD50, cpp, text_002DA0D0]
      - [0xFDE50, cpp, text_002DB1D0]
      - [0xFE8D0, cpp, text_002DBC50]
      - [0x1044F0, c, text_002E1870]
      - [0x1147A0, cpp, text_002F1B20]
      - [0x115F90, cpp, text_002F3310]
      - [0x11C910, cpp, text_002F9C90]
  - [0x123d80, bin, data]
  - name: init
    type: code
    start: 0x14d500
    vram: 0x32a880
    subalign: 16
    subsegments:
      - [0x14d500, cpp, init]
  - [0x14d540, bin, init_table]
  - [0x14d580]
