name: Star Ocean 3 US overlay citemcreation (0075-00, citemcreation.bin)
sha1: f63256304b18e3699ba338d35edc3fe156e5ece2
sha256: 14e5e5d822684823700136c9eaf5e9633f423edf6b5643061cc946f2db9bb217
options:
  basename: citemcreation
  target_path: disc/us-disc1/modules/0075-00.bin
  base_path: ../..
  platform: ps2
  compiler: MWCCPS2
  asm_path: build/overlays/citemcreation/asm
  asset_path: build/overlays/citemcreation/bin
  src_path: src/overlays/citemcreation
  build_path: build/overlays/citemcreation
  ld_script_path: build/overlays/citemcreation/overlay.ld
  generated_asm_macros_directory: build/overlays/citemcreation/include
  cache_path: build/overlays/citemcreation/splat.cache
  reloc_addrs_path: [config/relocations/citemcreation_reloc_addrs.txt]
  symbol_addrs_path: [config/symbols/citemcreation_symbol_addrs.txt]
  undefined_funcs_auto_path: build/overlays/citemcreation/undefined_funcs.ld
  undefined_syms_auto_path: build/overlays/citemcreation/undefined_syms.ld
  create_c_files: true
  make_full_disasm_for_code: true
  auto_decompile_empty_functions: false
  generated_c_preamble: '#include "include_asm.h"'
  asm_inc_header: |
    .set noat
    .set noreorder
  migrate_rodata_to_functions: false
  subalign: 4
  find_file_boundaries: false
  disasm_unknown: true
  gp_value: 0x1bdff0
  global_vram_start: 0x1B6430
  global_vram_end: 0x1B64FC
  generated_macro_inc_content: |
    .set Q, $Q
    .set ACC, $ACC
    .set I, $I
    .set R, $R
segments:
  - name: header
    type: bin
    start: 0x0
    vram: 0x348380
  - name: text
    type: code
    start: 0x40
    vram: 0x3483c0
    subalign: null
    subsegments:
      - [0x40, pad, text_start]
      - [0x80, cpp, text_003483C0]
      - [0x27040, pad, text_end]
      - [0x27080, databin, data]
      - [0x27260, .data, text_003483C0]
      - [0x27274, pad, data_pad_0036F5F4]
      - [0x27280, databin, data_0036F600]
      - start: 0x27300
        type: .rodata
        name: text_003483C0
        linker_section: .rodata.0036F680
        rodata_anchors:
          - {function: func_slotf4__22PendingInventorSummaryFPv, offset: 0x0, size: 0x38}
        linker_section_order: .rodata
      - [0x27338, pad, rodata_pad_0036F6B8]
      - start: 0x27340
        type: .rodata
        name: text_003483C0
        linker_section: .rodata.0036F6C0
        rodata_anchors:
          - {function: func_00349DE0, offset: 0x0, size: 0x38}
          - {function: func_0034FA70, offset: 0x40, size: 0x34}
        linker_section_order: .rodata
      - [0x273B4, rodatabin, rodata_0036F734]
      - start: 0x27440
        type: .rodata
        name: text_003483C0
        linker_section: .rodata.0036F7C0
        rodata_anchors:
          - {function: item_creation_update_skill_labels, offset: 0x0, size: 0x24}
          - {function: func_00361220, offset: 0x30, size: 0x3c}
          - {function: func_slotb0__20AssignedInventorGridFv, offset: 0x70, size: 0x34}
        linker_section_order: .rodata
      - [0x274E4, rodatabin, rodata_0036F864]
      - start: 0x274F0
        type: .rodata
        name: text_003483C0
        linker_section: .rodata.0036F870
        rodata_anchors:
          - {function: item_creation_initialize_expansion_costs, offset: 0x0, size: 0x34}
          - {function: item_creation_inventor_skill_message, offset: 0x40, size: 0x98}
          - {function: item_creation_inventor_skill_mask, offset: 0xe0, size: 0x98}
          - {function: func_0036BF30__32ItemCreationSelectedDisplayStateFib, offset: 0x180, size: 0x24}
        linker_section_order: .rodata
      - [0x27694, rodatabin, rodata_0036FA14]
  - [0x27700]
