name: Star Ocean 3 US main executable C scaffold
sha1: 1f8b172c0c2ff3f0b80bb6763077fdf33e271dcf
options:
  basename: main
  target_path: disc/us-disc1/iso/SLUS_204.88
  base_path: ..
  platform: ps2
  compiler: MWCCPS2
  asm_path: build/main/asm
  asset_path: build/main/bin
  src_path: src
  build_path: build/main
  ld_script_path: build/main/main.ld
  generated_asm_macros_directory: build/main/include
  cache_path: build/main/splat.cache
  symbol_addrs_path: [config/symbols/main_symbol_addrs.txt]
  undefined_funcs_auto_path: build/main/undefined_funcs.ld
  undefined_syms_auto_path: build/main/undefined_syms.ld
  create_c_files: true
  make_full_disasm_for_code: true
  auto_decompile_empty_functions: false
  generated_c_preamble: '#include "include_asm.h"'
  asm_inc_header: |
    .set noat
    .set noreorder
  migrate_rodata_to_functions: false
  subalign: 4
  find_file_boundaries: false
  disasm_unknown: true
  gp_value: 0x001BDFF0
  generated_macro_inc_content: |
    .set Q, $Q
    .set ACC, $ACC
    .set I, $I
    .set R, $R
segments:
  - [0x0, bin, elf_header]
  - name: resident
    type: code
    start: 0x680
    vram: 0x100000
    subsegments:
      - [0x680, asm, startup]
      - [0x860, c, main/resident_001001E0]
      - [0x18D0, c, main/func_00101250]
      - [0x18E0, c, main/resident_00101260]
      - [0x1B90, c, main/func_00101510]
      - [0x1BD0, c, main/resident_00101550]
      - [0xA700, c, main/func_0010A080]
      - [0xA730, c, main/func_0010A0B0]
      - [0xA760, c, main/resident_0010A0E0]
      - [0x1F480, c, main/func_0011EE00]
      - [0x1F4F0, c, main/resident_0011EE70]
      - [0x21FC0, c, sdk/main/libkernl_00121940]
      - [0x2B948, c, sdk/main/libdma_0012B2C8]
      - [0x2C190, c, sdk/main/libmc_0012BB10]
      - [0x2D980, c, sdk/main/libpad2_0012D300]
      - [0x2E238, c, sdk/main/libdbc_0012DBB8]
      - [0x2F148, c, sdk/main/libgraph_0012EAC8]
      - [0x30390, c, main/resident_0012FD10]
      - [0x30418, c, sdk/main/libgraph_0012FD98]
      - [0x305F8, c, main/resident_0012FF78]
      - [0x30680, c, sdk/main/libcdvd_00130000]
      - [0x32398, c, main/resident_00131D18]
      - [0x37540, c, sdk/main/libc_00136EC0]
      - [0x37560, c, main/resident_00136EE0]
      - [0x378D0, c, sdk/main/libc_00137250]
      - [0x37910, c, main/resident_00137290]
      - [0x3A9C8, c, sdk/main/libc_0013A348]
      - [0x3AB40, c, main/resident_0013A4C0]
      - [0x3CD50, c, sdk/main/libc_0013C6D0]
      - [0x3CFC8, c, main/resident_0013C948]
      - [0x3D0E0, c, sdk/main/libc_0013CA60]
      - [0x3D3D0, c, main/resident_0013CD50]
      - [0x3FA60, c, main/resident_0013F3E0]
      - [0x42F48, c, sdk/main/libvib_001428C8]
      - [0x430C0, c, main/resident_00142A40]
  - [0x44200, bin, resident_data]
  - [0xB6A80, bin, elf_metadata]
  - [0xB73B0]
